package app.mtt.aggrabandhu.dashboard.pages.profile

data class ProfileData(
    val aadharUrl: String,
    val aadhar_no: String,
    val address: String,
    val createdAt: String,
    val disease: Boolean,
    val diseaseFile: String,
    val district: String,
    val dob: String,
    val email: String,
    val father_name: String,
    val gotra: String,
    val id: Int,
    val id_file: String,
    val id_no: String,
    val id_type: String,
    val marital_status: String,
    val mobile_no: String,
    val mother_name: String,
    val name: String,
    val password: String,
    val pincode: String,
    val profession: String,
    val profileUrl: String,
    val reference_id: String,
    val rulesAccepted: Boolean,
    val spouse_name: String,
    val state: String,
    val status: String,
    val tahsil: String,
    val updatedAt: String,
    val nominees: List<Nominees>,
)

data class Nominees (
    val nominee : String,
    val relationship : String,
    val nominee2 : String,
    val relationship2 : String,
)